// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// AI
SEXP AI(SEXP Yin, SEXP Xin, SEXP numKin, SEXP Phiin, SEXP Din, SEXP tauin, SEXP fixtauin, SEXP tolin);
RcppExport SEXP MACAU2_AI(SEXP YinSEXP, SEXP XinSEXP, SEXP numKinSEXP, SEXP PhiinSEXP, SEXP DinSEXP, SEXP tauinSEXP, SEXP fixtauinSEXP, SEXP tolinSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type Yin(YinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Xin(XinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type numKin(numKinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Phiin(PhiinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Din(DinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type tauin(tauinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type fixtauin(fixtauinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type tolin(tolinSEXP);
    rcpp_result_gen = Rcpp::wrap(AI(Yin, Xin, numKin, Phiin, Din, tauin, fixtauin, tolin));
    return rcpp_result_gen;
END_RCPP
}
