# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

AI <- function(Yin, Xin, numKin, Phiin, Din, tauin, fixtauin, tolin) {
    .Call('MACAU2_AI', PACKAGE = 'MACAU2', Yin, Xin, numKin, Phiin, Din, tauin, fixtauin, tolin)
}

